"use client";

import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/wedgets/layout/Header/ui/Header";
import {usePathname} from "next/navigation";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children}: { children: React.ReactNode }) {

    const pathname = usePathname();

    // 로그인 페이지에서는 레이아웃 비활성화
    if (pathname === "/login" || pathname === "/login/signup") {
        return (
            <html lang="en">
                <body>
                    {children}
                </body>
            </html>
        );
    }

    return (
        <html lang="en">
            <body>
                <Header/>
                <main>{children}</main>
            </body>
        </html>
    );
}
